// Generated by gencpp from file ros_cellulo_swarm/cellulo_touch_key.msg
// DO NOT EDIT!


#ifndef ROS_CELLULO_SWARM_MESSAGE_CELLULO_TOUCH_KEY_H
#define ROS_CELLULO_SWARM_MESSAGE_CELLULO_TOUCH_KEY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_cellulo_swarm
{
template <class ContainerAllocator>
struct cellulo_touch_key_
{
  typedef cellulo_touch_key_<ContainerAllocator> Type;

  cellulo_touch_key_()
    : header()
    , keysTouched()  {
    }
  cellulo_touch_key_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , keysTouched(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _keysTouched_type;
  _keysTouched_type keysTouched;





  typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> const> ConstPtr;

}; // struct cellulo_touch_key_

typedef ::ros_cellulo_swarm::cellulo_touch_key_<std::allocator<void> > cellulo_touch_key;

typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_touch_key > cellulo_touch_keyPtr;
typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_touch_key const> cellulo_touch_keyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_cellulo_swarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ros_cellulo_swarm': ['/home/tprobotics/Documents/PROJECTS/catkin_ws/src/cellulo_swarm_practical_base/ros_cellulo_swarm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96a4e050938b99b4a757105a6b2a4c3d";
  }

  static const char* value(const ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96a4e050938b99b4ULL;
  static const uint64_t static_value2 = 0xa757105a6b2a4c3dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_cellulo_swarm/cellulo_touch_key";
  }

  static const char* value(const ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool[] keysTouched\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.keysTouched);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cellulo_touch_key_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_cellulo_swarm::cellulo_touch_key_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "keysTouched[]" << std::endl;
    for (size_t i = 0; i < v.keysTouched.size(); ++i)
    {
      s << indent << "  keysTouched[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.keysTouched[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_CELLULO_SWARM_MESSAGE_CELLULO_TOUCH_KEY_H
