// Generated by gencpp from file ros_cellulo_swarm/cellulo_vibrateOnMotion.msg
// DO NOT EDIT!


#ifndef ROS_CELLULO_SWARM_MESSAGE_CELLULO_VIBRATEONMOTION_H
#define ROS_CELLULO_SWARM_MESSAGE_CELLULO_VIBRATEONMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_cellulo_swarm
{
template <class ContainerAllocator>
struct cellulo_vibrateOnMotion_
{
  typedef cellulo_vibrateOnMotion_<ContainerAllocator> Type;

  cellulo_vibrateOnMotion_()
    : iCoeff(0.0)
    , period(0)  {
    }
  cellulo_vibrateOnMotion_(const ContainerAllocator& _alloc)
    : iCoeff(0.0)
    , period(0)  {
  (void)_alloc;
    }



   typedef float _iCoeff_type;
  _iCoeff_type iCoeff;

   typedef uint8_t _period_type;
  _period_type period;





  typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> const> ConstPtr;

}; // struct cellulo_vibrateOnMotion_

typedef ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<std::allocator<void> > cellulo_vibrateOnMotion;

typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_vibrateOnMotion > cellulo_vibrateOnMotionPtr;
typedef boost::shared_ptr< ::ros_cellulo_swarm::cellulo_vibrateOnMotion const> cellulo_vibrateOnMotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_cellulo_swarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ros_cellulo_swarm': ['/home/tprobotics/Documents/PROJECTS/catkin_ws/src/cellulo_swarm_practical_base/ros_cellulo_swarm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31f7864f30b1c9bccea79efef1e50285";
  }

  static const char* value(const ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31f7864f30b1c9bcULL;
  static const uint64_t static_value2 = 0xcea79efef1e50285ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_cellulo_swarm/cellulo_vibrateOnMotion";
  }

  static const char* value(const ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 iCoeff\n\
uint8 period\n\
";
  }

  static const char* value(const ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.iCoeff);
      stream.next(m.period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cellulo_vibrateOnMotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_cellulo_swarm::cellulo_vibrateOnMotion_<ContainerAllocator>& v)
  {
    s << indent << "iCoeff: ";
    Printer<float>::stream(s, indent + "  ", v.iCoeff);
    s << indent << "period: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_CELLULO_SWARM_MESSAGE_CELLULO_VIBRATEONMOTION_H
