# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_cellulo_swarm/CelluloStateRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CelluloStateRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "ros_cellulo_swarm/CelluloStateRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CelluloStateRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_cellulo_swarm/CelluloStateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class CelluloStateResponse(genpy.Message):
  _md5sum = "8bdab235f1da303d0e5f6b768207e8cb"
  _type = "ros_cellulo_swarm/CelluloStateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/TransformStamped Position
std_msgs/Float64 vy
std_msgs/Float64 vx
std_msgs/Float64 w
bool kidnapped
bool[] keysTouched
bool[] keysLongTouched


================================================================================
MSG: geometry_msgs/TransformStamped
# This expresses a transform from coordinate frame header.frame_id
# to the coordinate frame child_frame_id
#
# This message is mostly used by the 
# <a href="http://wiki.ros.org/tf">tf</a> package. 
# See its documentation for more information.

Header header
string child_frame_id # the frame id of the child frame
Transform transform

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['Position','vy','vx','w','kidnapped','keysTouched','keysLongTouched']
  _slot_types = ['geometry_msgs/TransformStamped','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','bool','bool[]','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Position,vy,vx,w,kidnapped,keysTouched,keysLongTouched

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CelluloStateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Position is None:
        self.Position = geometry_msgs.msg.TransformStamped()
      if self.vy is None:
        self.vy = std_msgs.msg.Float64()
      if self.vx is None:
        self.vx = std_msgs.msg.Float64()
      if self.w is None:
        self.w = std_msgs.msg.Float64()
      if self.kidnapped is None:
        self.kidnapped = False
      if self.keysTouched is None:
        self.keysTouched = []
      if self.keysLongTouched is None:
        self.keysLongTouched = []
    else:
      self.Position = geometry_msgs.msg.TransformStamped()
      self.vy = std_msgs.msg.Float64()
      self.vx = std_msgs.msg.Float64()
      self.w = std_msgs.msg.Float64()
      self.kidnapped = False
      self.keysTouched = []
      self.keysLongTouched = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.Position.header.seq, _x.Position.header.stamp.secs, _x.Position.header.stamp.nsecs))
      _x = self.Position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.Position.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10dB().pack(_x.Position.transform.translation.x, _x.Position.transform.translation.y, _x.Position.transform.translation.z, _x.Position.transform.rotation.x, _x.Position.transform.rotation.y, _x.Position.transform.rotation.z, _x.Position.transform.rotation.w, _x.vy.data, _x.vx.data, _x.w.data, _x.kidnapped))
      length = len(self.keysTouched)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.keysTouched))
      length = len(self.keysLongTouched)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.keysLongTouched))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.Position is None:
        self.Position = geometry_msgs.msg.TransformStamped()
      if self.vy is None:
        self.vy = std_msgs.msg.Float64()
      if self.vx is None:
        self.vx = std_msgs.msg.Float64()
      if self.w is None:
        self.w = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Position.header.seq, _x.Position.header.stamp.secs, _x.Position.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.Position.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.Position.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 81
      (_x.Position.transform.translation.x, _x.Position.transform.translation.y, _x.Position.transform.translation.z, _x.Position.transform.rotation.x, _x.Position.transform.rotation.y, _x.Position.transform.rotation.z, _x.Position.transform.rotation.w, _x.vy.data, _x.vx.data, _x.w.data, _x.kidnapped,) = _get_struct_10dB().unpack(str[start:end])
      self.kidnapped = bool(self.kidnapped)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.keysTouched = struct.unpack(pattern, str[start:end])
      self.keysTouched = map(bool, self.keysTouched)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.keysLongTouched = struct.unpack(pattern, str[start:end])
      self.keysLongTouched = map(bool, self.keysLongTouched)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.Position.header.seq, _x.Position.header.stamp.secs, _x.Position.header.stamp.nsecs))
      _x = self.Position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.Position.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10dB().pack(_x.Position.transform.translation.x, _x.Position.transform.translation.y, _x.Position.transform.translation.z, _x.Position.transform.rotation.x, _x.Position.transform.rotation.y, _x.Position.transform.rotation.z, _x.Position.transform.rotation.w, _x.vy.data, _x.vx.data, _x.w.data, _x.kidnapped))
      length = len(self.keysTouched)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.keysTouched.tostring())
      length = len(self.keysLongTouched)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.keysLongTouched.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.Position is None:
        self.Position = geometry_msgs.msg.TransformStamped()
      if self.vy is None:
        self.vy = std_msgs.msg.Float64()
      if self.vx is None:
        self.vx = std_msgs.msg.Float64()
      if self.w is None:
        self.w = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Position.header.seq, _x.Position.header.stamp.secs, _x.Position.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.Position.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.Position.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 81
      (_x.Position.transform.translation.x, _x.Position.transform.translation.y, _x.Position.transform.translation.z, _x.Position.transform.rotation.x, _x.Position.transform.rotation.y, _x.Position.transform.rotation.z, _x.Position.transform.rotation.w, _x.vy.data, _x.vx.data, _x.w.data, _x.kidnapped,) = _get_struct_10dB().unpack(str[start:end])
      self.kidnapped = bool(self.kidnapped)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.keysTouched = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.keysTouched = map(bool, self.keysTouched)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.keysLongTouched = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.keysLongTouched = map(bool, self.keysLongTouched)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10dB = None
def _get_struct_10dB():
    global _struct_10dB
    if _struct_10dB is None:
        _struct_10dB = struct.Struct("<10dB")
    return _struct_10dB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
class CelluloState(object):
  _type          = 'ros_cellulo_swarm/CelluloState'
  _md5sum = '8bdab235f1da303d0e5f6b768207e8cb'
  _request_class  = CelluloStateRequest
  _response_class = CelluloStateResponse
