// Generated by gencpp from file ros_cellulo/CelluloState.msg
// DO NOT EDIT!


#ifndef ROS_CELLULO_MESSAGE_CELLULOSTATE_H
#define ROS_CELLULO_MESSAGE_CELLULOSTATE_H

#include <ros/service_traits.h>


#include <ros_cellulo/CelluloStateRequest.h>
#include <ros_cellulo/CelluloStateResponse.h>


namespace ros_cellulo
{

struct CelluloState
{

typedef CelluloStateRequest Request;
typedef CelluloStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CelluloState
} // namespace ros_cellulo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_cellulo::CelluloState > {
  static const char* value()
  {
    return "8bdab235f1da303d0e5f6b768207e8cb";
  }

  static const char* value(const ::ros_cellulo::CelluloState&) { return value(); }
};

template<>
struct DataType< ::ros_cellulo::CelluloState > {
  static const char* value()
  {
    return "ros_cellulo/CelluloState";
  }

  static const char* value(const ::ros_cellulo::CelluloState&) { return value(); }
};


// service_traits::MD5Sum< ::ros_cellulo::CelluloStateRequest> should match 
// service_traits::MD5Sum< ::ros_cellulo::CelluloState > 
template<>
struct MD5Sum< ::ros_cellulo::CelluloStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_cellulo::CelluloState >::value();
  }
  static const char* value(const ::ros_cellulo::CelluloStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_cellulo::CelluloStateRequest> should match 
// service_traits::DataType< ::ros_cellulo::CelluloState > 
template<>
struct DataType< ::ros_cellulo::CelluloStateRequest>
{
  static const char* value()
  {
    return DataType< ::ros_cellulo::CelluloState >::value();
  }
  static const char* value(const ::ros_cellulo::CelluloStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_cellulo::CelluloStateResponse> should match 
// service_traits::MD5Sum< ::ros_cellulo::CelluloState > 
template<>
struct MD5Sum< ::ros_cellulo::CelluloStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_cellulo::CelluloState >::value();
  }
  static const char* value(const ::ros_cellulo::CelluloStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_cellulo::CelluloStateResponse> should match 
// service_traits::DataType< ::ros_cellulo::CelluloState > 
template<>
struct DataType< ::ros_cellulo::CelluloStateResponse>
{
  static const char* value()
  {
    return DataType< ::ros_cellulo::CelluloState >::value();
  }
  static const char* value(const ::ros_cellulo::CelluloStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_CELLULO_MESSAGE_CELLULOSTATE_H
