(cl:defpackage ros_cellulo-msg
  (:use )
  (:export
   "<CELLULO_COORD>"
   "CELLULO_COORD"
   "<CELLULO_KIDNAPPED_MSG>"
   "CELLULO_KIDNAPPED_MSG"
   "<CELLULO_POSE_VELOCITY>"
   "CELLULO_POSE_VELOCITY"
   "<CELLULO_SIMPLEVIBRATE>"
   "CELLULO_SIMPLEVIBRATE"
   "<CELLULO_TOUCH_KEY>"
   "CELLULO_TOUCH_KEY"
   "<CELLULO_VIBRATEONMOTION>"
   "CELLULO_VIBRATEONMOTION"
   "<CELLULO_VISUAL_EFFECT>"
   "CELLULO_VISUAL_EFFECT"
  ))

